# Generated by Django 2.0.8 on 2018-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='код')),
                ('content_xml', models.TextField(verbose_name='XML содержимое')),
                ('content_json', models.TextField(verbose_name='JSON содержимое')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='названиеи')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='код')),
                ('content_xml', models.TextField(verbose_name='XML содержимое')),
                ('content_json', models.TextField(verbose_name='JSON содержимое')),
                ('modules', models.ManyToManyField(to='core.Module')),
            ],
        ),
    ]
